language: node_js
node_js:
  - "--lts"
cache: yarn

before_install:
  - npm install -g yarn
  - npm install -g elm
  - npm install -g elm-test

before_script:
  - elm-make --yes

script:
  - yarn build
  - yarn test

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  on:
    branch: gh-pages
