language: node_js
node_js:
  - "--lts"
cache: yarn

before_install:
  - npm install -g yarn
  - npm install -g elm

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  on:
    branch: gh-pages
